import ColumnLayout from "components/ColumnLayout";
import StudentRegister from "components/registration/StudentRegister";
import Head from "next/head";

export default function Student() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ColumnLayout>
        <StudentRegister />
      </ColumnLayout>
    </>
  );
}
