import Head from "next/head";
import styled from "styled-components";
import Image from "next/image";

import Login from "components/Login";
import { useRouter } from "next/router";

const buttons = [
  {
    id: 1,
    name: "Register As Student",
    link: "register/student",
  },
  {
    id: 2,
    name: "Register As Coach",
    link: "register/coach",
  },
  {
    id: 3,
    name: "Register as Certified Black Belt",
    link: "register/black-belt",
  },
  {
    id: 4,
    name: "Register As Judge / Refree",
    link: "register/judge",
  },
];

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>World Modern Shotokan Karate Federation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageWrapper>
        <Image
          src="/images/bg.jpg"
          layout="fill"
          objectFit="cover"
          objectPosition="top center"
          alt="two players practising karate"
        />
        <div className="screen" />

        <ContentWrapper>
          <Image
            src="/images/logo.png"
            alt="Image of guys practicing karate"
            width={155}
            height={147}
            style={{ marginBottom: "2rem" }}
          />
          <div className="form-and-buttons">
            <div className="buttons">
              {buttons.map((button) => (
                <Button
                  key={button.id}
                  onClick={() => router.push(button.link)}
                >
                  {button.name}
                </Button>
              ))}
            </div>

            <div className="form">
              <Login />
            </div>
          </div>
        </ContentWrapper>
      </PageWrapper>
    </>
  );
}

const PageWrapper = styled.main`
  .screen {
    position: absolute;
    inset: 0;
    background: rgba(0, 0, 0, 0.6);
  }

  display: flex;
  align-items: center;
  height: 100vh;
  overflow: scroll;
`;

const ContentWrapper = styled.div`
  position: relative;
  z-index: 5;
  background: rgba(255, 255, 255, 0.95);
  border-radius: 5px;
  overflow: scroll;

  width: 95%;
  max-width: 80rem;
  max-height: 90vh;
  margin: 0 auto;

  display: grid;
  justify-items: center;
  padding: 1rem;

  .form-and-buttons {
    display: flex;
    flex-direction: column-reverse;

    @media (min-width: 1024px) {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 5rem;
    }
  }
`;

const Button = styled.button`
  font-size: 1rem;
  font-family: inherit;
  width: 100%;
  height: 3.5em;

  background: ${({ theme }) => theme.blue};
  color: ${({ theme }) => theme.primary};
  border: none;
  margin-bottom: 2rem;
  border-radius: 16px;
`;
