import Head from "next/head";
import styled from "styled-components";

import { useRouter } from "next/router";
import Image from "next/image";
import PersonalInfo from "components/dashboard/PersonalInfo";
import About from "components/dashboard/About";
import IdCard from "components/dashboard/IDCard";
import { useAuth } from "context/User";
import { GetServerSideProps } from "next";
import { doc, DocumentData, getDoc } from "firebase/firestore";
import { db } from "firebase.config";

const Container = styled.main`
  width: 90%;
  max-width: 80rem;
  padding: 1rem 0;

  margin: 0 auto;

  header {
    display: grid;
    grid-template-columns: 1fr 9fr;

    align-items: center;

    h1 {
      font-size: 1.125rem;
      font-weight: 600;
      margin-bottom: 0.5rem;
    }

    span {
      font-size: 0.9rem;
      opacity: 0.8;
    }

    @media (min-width: 425px) {
      h1 {
        font-size: 1.5rem;
      }

      span {
        font-size: 1rem;
      }
    }
  }
`;

const TopSection = styled.div`
  margin: 1rem 0;
  gap: 1rem;
  display: grid;
  @media (min-width: 767px) {
    grid-template-columns: 2fr 1fr;
  }
`;

export default function Home({ data }: DocumentData) {
  const user = useAuth();
  data = JSON.parse(data);

  if (!user) {
    return <div></div>;
  }

  return (
    <>
      <Head>
        <title>World Modern Shotokan Karate Federation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <header>
          <div className="image">
            <Image
              src="/images/logo.png"
              alt="Image of guys practicing karate"
              width={85}
              height={87}
            />
          </div>
          <div className="content">
            <h1>Welcome to WMSKF Portal , Vishal</h1>
            <span>Tue, 07 June 2022</span>
          </div>
        </header>

        <TopSection>
          <PersonalInfo data={data} />
          <About data={data} />
          <div></div>
          <IdCard data={data} />
        </TopSection>
      </Container>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { uid } = context.query;

  const docRef = doc(db, "users", uid as string);
  const docSnap = await getDoc(docRef);

  const data = docSnap.data();

  return {
    props: { data: JSON.stringify({ ...data, id: docSnap.id }) },
  };
};
