import Head from "next/head";

import ColumnLayout from "components/ColumnLayout";
import CoachPersonalForm from "components/personal/Coach";

export default function Coach() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ColumnLayout>
        <CoachPersonalForm />
      </ColumnLayout>
    </>
  );
}
